#!/usr/bin/php
<?php

function read_files($folder, &$tab)
{
    if ($handle = opendir($folder)) {

        while (false !== ($file = readdir($handle))) {
            if ($file == '.' || $file == '..') continue;
            if (is_dir($folder . "/" . $file)) {
                read_files($folder . "/" . $file, $tab);
            }
            else if (strrpos($file, '.png') > -1) {
                array_push($tab, $folder . "/" . $file);
            }
        }
    }
}
function getSizeOfSprite($tab) {

    $totalLargeur = 0;
    $maxHauteur = [];

    for ($i = 0; $i < count($tab); $i++) {
        $tmp = getimagesize($tab[$i]);
        $totalLargeur += $tmp[0];
        array_push($maxHauteur, $tmp[1]);
    }
    $maxHauteurValue = max($maxHauteur);
    $sprite = imagecreatetruecolor($totalLargeur, $maxHauteurValue);
    imagealphablending($sprite, false);
    $col=imagecolorallocatealpha($sprite,255,255,255,127);
    imagefilledrectangle($sprite,0,0,$totalLargeur, $totalLargeur,$col);
    imagealphablending($sprite,true);


    create_sprite($tab, $sprite);
}


function create_sprite(&$tab, &$sprite){

    static $largerX = 0;

    foreach ($tab as $value) {
        $png = imagecreatefrompng($value);
        $tmp = getimagesize($value);
        imagecopy($sprite, $png, $largerX, 0, 0, 0, $tmp[0], $tmp[1]);
        $largerX += $tmp[0];
    }
    imagepng($sprite, 'image_3.png');
}


function create_css(&$tab)
{
    if (!file_exists('stylesheet.css')) {
        $all_values = [];
//    $name=[];

        foreach ($tab as $value) {
            $tmp = getimagesize($value);
            array_push($all_values, $tmp);
        }

        for ($i = 0; $i < count($tab); $i++) {
//    $name=$tab[0];
//    $implode = implode("\n", $name);
//        array_push($name,$tab[$i]);
        }
//        var_dump($name);

//  print_r($all_values);
        for ($i = 0; $i < count($all_values); $i++) {
//        $premier = $all_values[$i];
//        var_dump($premier);

            static $lol = 1;

            $hauteur = "#image" . $lol . " { \n"
                . "width :" . $all_values[$i][0] . " px; \n"
                . "height :" . $all_values[$i][1] . " px; \n" . "\n";
            $lol++;
//        var_dump($hauteur);

            file_put_contents('stylesheet.css', $hauteur, FILE_APPEND);
        }
    }
}






$tab = array();
read_files($argv[1], $tab);
getSizeOfSprite($tab);

create_css($tab);


