#!/usr/bin/php
<?php
include "css_generator_2.php";

function get_arg($argv, &$tab){
    $pos_option = "";
    $pos_folder = "";

    for ($i = 0; $i < count($argv); $i++) {
        if ($argv[$i] =='-r'|| $argv[$i] == "--recursive") {
            $pos_option = '-r';
        }
        else if (is_dir($argv[$i])){
            $pos_folder = $i;
        }
    }
    read_files($argv[$pos_folder], $tab, $pos_option);
}


function read_files($folder, &$tab,$pos_option)
{
    if ($handle = opendir($folder)) {

        while (false !== ($file = readdir($handle))) {
            if ($file == '.' || $file == '..') continue;
            else if (mime_content_type($folder . "/" . $file) == 'image/png') {
                array_push($tab, $folder . "/" . $file);;
            }
            if ($pos_option == "-r") {
                if (is_dir($folder . "/" . $file)) {
                    read_files($folder . "/" . $file, $tab, $pos_option);
                }
            }
        }
    }
}
function getSizeOfSprite($tab) {

    $total_height = 0;
    $maxHeight = [];

    for ($i = 0; $i < count($tab); $i++) {
        $tmp = getimagesize($tab[$i]);
        $total_height += $tmp[0];
        array_push($maxHeight, $tmp[1]);
    }
    $maxHauteurValue = max($maxHeight);
    $sprite = imagecreatetruecolor($total_height, $maxHauteurValue);
    imagealphablending($sprite, false);
    $col=imagecolorallocatealpha($sprite,255,255,255,127);
    imagefilledrectangle($sprite,0,0,$total_height, $total_height,$col);
    imagealphablending($sprite,true);


    create_sprite($tab, $sprite);
}


function create_sprite(&$tab, &$sprite){

    static $largerX = 0;

    foreach ($tab as $value) {
        $png = imagecreatefrompng($value);
        $tmp = getimagesize($value);
        imagecopy($sprite, $png, $largerX, 0, 0, 0, $tmp[0], $tmp[1]);
        $largerX += $tmp[0];
    }
    imagepng($sprite, 'sprite.png');
}


function create_css(&$tab){
    $all_values = [];
    if (!file_exists('style.css')) {
        for ($i = 0; $i < count($tab); $i++) {
            $tmp = getimagesize($tab[$i]);
            array_push($all_values, $tmp);;
            $path = explode("/", $tab[$i]);
            $path = end($path);
            $path =str_replace(".","_" ,$path );

            static $back_pos = 0;
            $height = "#" .$path. "{\n"."width :".$all_values[$i][0]."px;\n"
               ."height :".$all_values[$i][1]."px;\n"."display:inline-block;\n"
                ."background-repeat: no-repeat; \n"
                ."background-position: -" .$back_pos ." 0px; \n"
                ."background-image: url('sprite.png');" ."\n}" ."\n \n" ;
            $back_pos += $all_values[$i][0];
            file_put_contents('style.css', $height, FILE_APPEND);
        }
    }
    else if(file_exists('style.css')){
        unlink('style.css');
        create_css($tab);
    }
}


$tab = array();
get_arg($argv, $tab);
getSizeOfSprite($tab);
output_style($argv,$tab,$input);
output_image($argv, $tab, $folder, $pos_option);
